# Generated by Django 3.2.3 on 2021-05-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norilog', '0002_noriori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noriori',
            options={'verbose_name': '乗降履歴', 'verbose_name_plural': '乗降履歴'},
        ),
    ]
